### PR TITLE
Update package template for Intern 4

### LINKED ISSUE #94: Update to intern 4
**Enhancement**

Update package to use intern 4 and remove the associated intern 3 configuration / ignored files from `.gitignore`

### PR DESCRIPTION
**Pull request by bryanforbes**
**Type:** enhancement

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

Updates template to Intern 4

Resolves #94

### CODE REVIEW

**Comment by kitsonk** [comment]
I think we need a fix for theintern/intern#826 before we finalise this update, so the `tests/run.html` is _hacky_...

**Comment by bryanforbes** [comment]
> I think we need a fix for theintern/intern#826 before we finalise this update, so the tests/run.html is hacky...

I agree. We'll hold off until that lands.

**Review by kitsonk — APPROVED** [review]
This should be good to go now, right?

**Comment by bryanforbes** [comment]
This also took care of dojo/meta#211

**Pull request merged**
