### PR TITLE
Prefer files in package.json over .npmignore

### LINKED ISSUE #42: Consider using "files" in package.json rather than .npmignore
`.npmignore` is a blacklist, `files` is a whitelist.

It's hard to maintain a blacklist, e.g. `/html-report` is missing from `.npmignore` currently. Blacklists don't account for any temporary files the publisher may have either.

Given the consistent build output it should be a lot easier to maintain the `files` whitelist.

https://docs.npmjs.com/files/package.json#files

### PR DESCRIPTION
**Pull request by novemberborn**
`index.js` is for Node.js targets and simply loads `dist/umd/main`. `dist` includes the distributed files. Source maps contain original sources so the `src` directory does not need to be included.

I'm assuming `bower.json` is only needed in GitHub, not in npm.

Fixes #42.

---

Before:

```
$ tar tvf dojo-app-2.0.0-pre.tgz
-rw-r--r--  0 501    20       1284 20 Jun 15:59 package/package.json
-rw-r--r--  0 501    20      15510 20 Jun 17:53 package/README.md
-rw-r--r--  0 501    20       1562 17 May 15:18 package/LICENSE
-rw-r--r--  0 501    20         48 16 Jun 18:37 package/index.js
-rw-r--r--  0 501    20         46 16 Jun 18:37 package/codecov.yml
-rw-r--r--  0 501    20        400 16 Jun 18:37 package/bower.json
-rw-r--r--  0 501    20       4922 22 Jun 11:08 package/dist/umd/IdentityRegistry.js
-rw-r--r--  0 501    20       7482 22 Jun 11:08 package/dist/umd/_factories.js
-rw-r--r--  0 501    20       1098 22 Jun 11:08 package/dist/umd/_moduleResolver.js
-rw-r--r--  0 501    20      16959 22 Jun 11:08 package/dist/umd/_realizeCustomElements.js
-rw-r--r--  0 501    20       2132 22 Jun 11:08 package/dist/umd/_resolveListenersMap.js
-rw-r--r--  0 501    20      11417 22 Jun 11:08 package/dist/umd/createApp.js
-rw-r--r--  0 501    20        502 22 Jun 11:08 package/dist/umd/main.js
-rw-r--r--  0 501    20       6447 22 Jun 11:08 package/dist/umd/_debug/IdentityRegistry.js.map
-rw-r--r--  0 501    20      12776 22 Jun 11:08 package/dist/umd/_debug/_factories.js.map
-rw-r--r--  0 501    20       1380 22 Jun 11:08 package/dist/umd/_debug/_moduleResolver.js.map
-rw-r--r--  0 501    20      24671 22 Jun 11:08 package/dist/umd/_debug/_realizeCustomElements.js.map
-rw-r--r--  0 501    20       3361 22 Jun 11:08 package/dist/umd/_debug/_resolveListenersMap.js.map
-rw-r--r--  0 501    20      28014 22 Jun 11:08 package/dist/umd/_debug/createApp.js.map
-rw-r--r--  0 501    20        243 22 Jun 11:08 package/dist/umd/_debug/main.js.map
-rw-r--r--  0 501    20      16464 22 Jun 11:08 package/dist/umd/dojo-app.d.ts
-rw-r--r--  0 501    20      17569 20 Jun 17:45 package/html-report/prettify.js
-rw-r--r--  0 501    20       5174 20 Jun 17:45 package/html-report/sorter.js
-rw-r--r--  0 501    20       5057 20 Jun 17:45 package/html-report/base.css
-rw-r--r--  0 501    20       3662 20 Jun 17:45 package/html-report/index.html
-rw-r--r--  0 501    20        676 20 Jun 17:45 package/html-report/prettify.css
-rw-r--r--  0 501    20        209 20 Jun 17:45 package/html-report/sort-arrow-sprite.png
-rw-r--r--  0 501    20      54176 25 May 10:19 package/html-report/src/App.ts.html
-rw-r--r--  0 501    20      13308 20 Jun 17:45 package/html-report/src/IdentityRegistry.ts.html
-rw-r--r--  0 501    20      20621 20 Jun 17:45 package/html-report/src/_factories.ts.html
-rw-r--r--  0 501    20       4590 20 Jun 17:45 package/html-report/src/_moduleResolver.ts.html
-rw-r--r--  0 501    20      36456 20 Jun 17:45 package/html-report/src/_realizeCustomElements.ts.html
-rw-r--r--  0 501    20       6588 20 Jun 17:45 package/html-report/src/_resolveListenersMap.ts.html
-rw-r--r--  0 501    20      55523 20 Jun 17:45 package/html-report/src/createApp.ts.html
-rw-r--r--  0 501    20       7914 20 Jun 17:45 package/html-report/src/index.html
-rw-r--r--  0 501    20       2398 20 Jun 17:45 package/html-report/src/main.ts.html
-rw-r--r--  0 501    20        195 17 May 15:18 package/CONTRIBUTING.md
-rw-r--r--  0 501    20       3589 17 Jun 16:40 package/src/IdentityRegistry.ts
-rw-r--r--  0 501    20       7006 20 Jun 17:53 package/src/_factories.ts
-rw-r--r--  0 501    20        701 17 Jun 16:40 package/src/_moduleResolver.ts
-rw-r--r--  0 501    20      12572 20 Jun 17:53 package/src/_realizeCustomElements.ts
-rw-r--r--  0 501    20       1416 20 Jun 17:53 package/src/_resolveListenersMap.ts
-rw-r--r--  0 501    20      18631 20 Jun 17:53 package/src/createApp.ts
-rw-r--r--  0 501    20         60 16 Jun 18:37 package/src/main.ts
-rw-r--r--  0 501    20       1865 20 Jun 15:59 package/typings.json
```

After:

```
$ tar tvf dojo-app-2.0.0-pre.tgz
-rw-r--r--  0 501    20       1323 22 Jun 11:12 package/package.json
-rw-r--r--  0 501    20      15510 20 Jun 17:53 package/README.md
-rw-r--r--  0 501    20       1562 17 May 15:18 package/LICENSE
-rw-r--r--  0 501    20         48 16 Jun 18:37 package/index.js
-rw-r--r--  0 501    20       4922 22 Jun 11:13 package/dist/umd/IdentityRegistry.js
-rw-r--r--  0 501    20       7482 22 Jun 11:13 package/dist/umd/_factories.js
-rw-r--r--  0 501    20       1098 22 Jun 11:13 package/dist/umd/_moduleResolver.js
-rw-r--r--  0 501    20      16959 22 Jun 11:13 package/dist/umd/_realizeCustomElements.js
-rw-r--r--  0 501    20       2132 22 Jun 11:13 package/dist/umd/_resolveListenersMap.js
-rw-r--r--  0 501    20      11417 22 Jun 11:13 package/dist/umd/createApp.js
-rw-r--r--  0 501    20        502 22 Jun 11:13 package/dist/umd/main.js
-rw-r--r--  0 501    20       6447 22 Jun 11:13 package/dist/umd/_debug/IdentityRegistry.js.map
-rw-r--r--  0 501    20      12776 22 Jun 11:13 package/dist/umd/_debug/_factories.js.map
-rw-r--r--  0 501    20       1380 22 Jun 11:13 package/dist/umd/_debug/_moduleResolver.js.map
-rw-r--r--  0 501    20      24671 22 Jun 11:13 package/dist/umd/_debug/_realizeCustomElements.js.map
-rw-r--r--  0 501    20       3361 22 Jun 11:13 package/dist/umd/_debug/_resolveListenersMap.js.map
-rw-r--r--  0 501    20      28014 22 Jun 11:13 package/dist/umd/_debug/createApp.js.map
-rw-r--r--  0 501    20        243 22 Jun 11:13 package/dist/umd/_debug/main.js.map
-rw-r--r--  0 501    20      16464 22 Jun 11:13 package/dist/umd/dojo-app.d.ts
```

### CODE REVIEW

**Comment by kitsonk** [comment]
`typings.json` needs to be included as part of the package...  I also wanted to include `src` as it can often contain the necessary code to further integrate into tooling without having to grab the package from GitHub.  Not only does it contain the source files, but for example with `dojo/widgets` it contains the source `.styl` files which is very useful for other toolchains building CSS.

**Comment by novemberborn** [comment]
> typings.json needs to be included as part of the package...

Why? I could link my `app-example` against a packed `dojo-app` without it. The `package.json` has the pointer to the distribution type definition.

> I also wanted to include src as it can often contain the necessary code to further integrate into tooling without having to grab the package from GitHub. Not only does it contain the source files, but for example with dojo/widgets it contains the source .styl files which is very useful for other toolchains building CSS.

Cool will add it. Was unsure about leaving it out.

**Comment by kitsonk** [comment]
> Why? I could link my app-example against a packed dojo-app without it. The package.json has the pointer to the distribution type definition.

But the `typings.json` expresses other external dependencies when requiring the package, so `typings/typings` can build an entire set (it also does duplication elimination and version conflicts of typings).

**Comment by agubler** [comment]
> But the `typings.json` expresses other external dependencies when requiring the package, so `typings/typings` can build an entire set (it also does duplication elimination and version conflicts of typings).

If this works then it will make it much easier to consume the modules, does it only do it for the `dependencies` and not the `devDependencies`? does it also respect the `globalDependencies`?

**Comment by kitsonk** [comment]
> If this works then it will make it much easier to consume the modules, does it only do it for the `dependencies` and not the `devDependencies`? does it also respect the `globalDependencies`?

I *think* so, but the [`typings/typings` FAQ](https://github.com/typings/typings/blob/master/docs/faq.md#should-i-use-the-typings-field-in-packagejson) indicates that is the reason why.

**Comment by novemberborn** [comment]
This was updated by the way.

**Pull request merged**
